blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

products/urls.py
from django.urls import path
from .views import ShopListView, ShopDetailView


app_name = 'products'


urlpatterns = [
    path('', ShopListView.as_view(), name='shop-list'),
    path('<slug:slug>/', ShopListView.as_view(), name='filter-list'),
    path('details/<slug:slug>/', ShopDetailView.as_view(), name='shop-detail'),
]

project/urls.py
from core.views import handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('products/', include('products.urls', namespace='products')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('main.urls', namespace='main')),

    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1)
    override = forms.BooleanField(required=False,  initial=False,  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')



@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')



def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={ 'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>Your shopping cart</title>
{% endblock %}

{% block content %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Shopping Cart</h4>
                    <div class="breadcrumb__links">
                        <a href="/">Home</a>
                        <a href="{% url 'products:shop-list' %}">Shop</a>
                        <span>Shopping Cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shopping Cart Section Begin -->
<section class="shopping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="shopping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                            {% with product=item.product %}
                            <tr>
                                <td class="product__cart__item">
                                    <div class="product__cart__item__pic">
                                        <a href="{{ product.get_absolute_url }}">
                                            <img src="{% for img in product.product_img.all %}{% if forloop.last %}{{img.image.url}}{% endif%} {% endfor %}"
                                                alt="product cart">
                                        </a>
                                    </div>
                                    <div class="product__cart__item__text">
                                        <h6>{{product}}</h6>
                                    </div>
                                </td>
                                <td class="quantity__item">
                                    <div class="quantity">
                                        <form id="update" action="{% url 'cart:cart_add' product.id %}" method="post">
                                            <div class="pro-qty-2">
                                                {{ item.update_quantity_form.quantity }}
                                            </div>
                                                {{ item.update_quantity_form.override }}
                                            {% csrf_token %}
                                        </form>
                                    </div>
                                </td>
                                <td class="cart__price">$ {{item.price}}</td>
                                <td class="cart__price">${{ item.total_price }}</td>
                                <td class="cart__close">
                                    <form action='{% url "cart:cart_remove" product.id %}' method="post">
                                    <button type="submit" class="cart__close"><i class="fa fa-close"></i></button>
                                    {% csrf_token %}
                                    </form>
                                </td>
                            </tr>
                            {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="continue__btn">
                            <a href="{% url 'products:shop-list' %}">Continue Shopping</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="continue__btn update__btn">
                            <button type="submit" form="update"><i class="fa fa-spinner"></i> Update cart</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart__discount">
                    <h6>Discount codes</h6>
                    <form action="#">
                        <input type="text" placeholder="Coupon code">
                        <button type="submit">Apply</button>
                    </form>
                </div>
                <div class="cart__total">
                    <h6>Cart total</h6>
                    <ul>
                        <li>Total <span>$ {{ cart.get_total_price }}</span></li>
                    </ul>
                    <a href="#" class="primary-btn">Proceed to checkout</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shopping Cart Section End -->



{% endblock %}