blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
]

main/urls.py
from django.urls import path
from .views import index, content, about

app_name = 'main'


urlpatterns = [
    path('', index, name='home'),
    path('contact-us/', content, name='contact'),
    path('about-us/', about, name='about'),
]

products/urls.py
from django.urls import path
from .views import ShopListView, ShopDetailView


app_name = 'products'


urlpatterns = [
    path('', ShopListView.as_view(), name='shop-list'),
    path('<slug:slug>/', ShopListView.as_view(), name='filter-list'),
    path('details/<slug:slug>/', ShopDetailView.as_view(), name='shop-detail'),
]

project/urls.py
from core.views import handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('products/', include('products.urls', namespace='products')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('main.urls', namespace='main')),

    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

templates/base/css.html
{% load static %}
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

templates/base/footer.html
{% load static %}
<!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="/"><img src="{{main.logo.url}}" alt="logo"></a>
                        </div>
                            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</p>
                        <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="{% url 'products:filter-list' 'clothing' %}">Clothing Store</a></li>
                            <li><a href="{% url 'products:filter-list' 'shoes' %}">Shoes</a></li>
                            <li><a href="{% url 'products:filter-list' 'accessories' %}">Accessories</a></li>
                            <li><a href="#">Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Delivary</a></li>
                            <li><a href="#">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <p>Copyright ©
                            {{current_year}}
                            All rights reserved | Back-End made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="{{main.facebook}}" target="_blank">
                            <img style="width:35px; height:35px; object-fit:cover" src="{% static 'img/logoback.png' %}">
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

templates/base/js.html
{% load static %}
   <!-- Js Plugins -->
   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
   <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
   <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
   <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
   <script src="{% static 'js/jquery.slicknav.js' %}"></script>
   <script src="{% static 'js/mixitup.min.js' %}"></script>
   <script src="{% static 'js/owl.carousel.min.js' %}"></script>
   <script src="{% static 'js/main.js' %}"></script>

templates/base/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li style="color:green;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/base/navbar.html
{% load static %}
    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__option">
            <div class="offcanvas__links">
                <a href="#">Sign in</a>
                <a href="#">FAQs</a>
            </div>
            <div class="offcanvas__top__hover">
                <span>Usd <i class="arrow_carrot-down"></i></span>
                <ul>
                    <li>USD</li>
                    <li>EUR</li>
                    <li>USD</li>
                </ul>
            </div>
        </div>
        <div class="offcanvas__nav__option">
            <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
            <div class="price">$0.00</div>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__text">
            <p>Free shipping, 30-day return or refund guarantee.</p>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-7">
                        <div class="header__top__left">
                            <p>Free shipping, 30-day return or refund guarantee.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-5">
                        <div class="header__top__right">
                            <div class="header__top__links">
                                <a href="#">Sign in</a>
                                <a href="#">FAQs</a>
                            </div>
                            <div class="header__top__hover">
                                <span>Usd <i class="arrow_carrot-down"></i></span>
                                <ul>
                                    <li>USD</li>
                                    <li>EUR</li>
                                    <li>USD</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="header__logo">
                        <a href="/"><img src="{{main.logo.url}}" alt="logo"></a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li class="active"><a href="/">Home</a></li>
                            <li><a href="{% url 'products:shop-list' %}">Shop</a></li>
                            <li><a href="{% url 'main:about' %}">About Us</a></li>
                            <li><a href="{% url 'blog:post-list' %}">Blog</a></li>
                            <li><a href="{% url 'main:contact' %}">Contacts</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3 col-md-3">
                    <div class="header__nav__option">
                        <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
                        <div class="price">$0.00</div>
                    </div>
                </div>
            </div>
            <div class="canvas__open"><i class="fa fa-bars"></i></div>
        </div>
    </header>
    <!-- Header Section End -->

templates/base/pagination.html
{% if is_paginated %}
    <div class="row">
        <div class="col-lg-12">
            <div class="product__pagination">
                {% if page_obj.has_previous %}
                <a class="active" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                {% else %}
                <a class="disabled"><span>&laquo;</span></a>
                {% endif %}

                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <a class="active"><span>{{ i }}</span></a>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                {% else %}
                <a class="disabled"><span>&raquo;</span></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endif %}